### ISSUE TITLE
Error message with scifact_joint_paragraph_dynamic_prediction.py

### ISSUE THREAD

**Issue by wjddd** [jacklxc/ParagraphJointModel#2]
Hi,

When I ran scifact_joint_paragraph_dynamic_prediction.py, I got this error message:

Traceback (most recent call last):
  File "scifact_joint_paragraph_dynamic_prediction.py", line 26, in <module>
    from lib.data import GoldDataset, PredictedDataset
ModuleNotFoundError: No module named 'lib.data'

Could you please help me with this ?

**Comment by jacklxc** [comment]
Hi, thanks for pointing it out. lib/ is the module developed by SciFact authors to measure the model performance. I forgot to push them here. I've added it back.
