### ISSUE TITLE
Evaluation code for abstract retrieval

### ISSUE THREAD

**Issue by Eiriksak** [jacklxc/ParagraphJointModel#4]
Hi, I am wondering if the code you used for abstract retrieval performance is available somewhere? I am trying to reproduce the R@k results from table 2, but my results are slightly different.

**Comment by jacklxc** [comment]
Unfortunately, I don't have the exact evaluation code, but the original code is borrowed from SciFact's earlier version of the evaluation code (https://github.com/allenai/scifact/tree/master/verisci/evaluate). You can easily code up the evaluation code by yourself. If your results are "slightly" different, it's not surprising.
