### ISSUE TITLE
I need to use the checkpoint you have on Google Drive

### ISSUE THREAD

**Issue by 15963064649** [jacklxc/ParagraphJointModel#8]
Hello, I am very interested in your work and am currently reproducing the work found at [https://aclanthology.org/2022.acl-long.175/](https://aclanthology.org/2022.acl-long.175/). I need to use the checkpoint you have on Google Drive, but I couldn't find it in the link provided. Could you please share a copy with me? Thank you.

**Comment by jacklxc** [comment]
Hi, as you can easily tell, I am not the author of this paper. I happened to present it at my lab meeting long ago though. This work didn't even use my model for their experiment.

On the other hand, this paper is based on old approaches before LLM became popular. Nowadays I think it's much easier to use LLM for zero-shot predictions of claim verifications.

**Comment by 15963064649** [comment]
Apologies for the interruption, thank you for your reply. I have understood your point. I am currently working on some fact-checking tasks and happen to need the resources from this paper. As you mentioned, using Large Language Models (LLMs) is a great approach, but I need to verify the validity of the claims through fact-checking.










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jacklxc/ParagraphJointModel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jacklxc/ParagraphJointModel] I need to use the checkpoint you have on Google Drive (Issue #8)





 
Hi, as you can easily tell, I am not the author of this paper. I happened to present it at my lab meeting long ago though. This work didn't even use my model for their experiment.
 
On the other hand, this paper is based on old approaches before LLM became popular. Nowadays I think it's much easier to use LLM for zero-shot predictions of claim verifications.
